export const SALE_RANKING = "SALE_RANKING"
export const FETCH_cOLLECTON = "FETCH_cOLLECTON" ;
export const ANALYSIS_BOARD = "ANALYSIS_BOARD";
export const ASSETS_FOR_SALE = "ASSETS_FOR_SALE";
export const FLOOR_PRICE = "FLOOR_PRICE";
export const GET_CURRENT_LIST = "GET_CURRENT_LIST"